# Generated by `skaal deploy --target gcp` (WSGI mode).
# Serves the user's WSGI app (e.g. Dash/Flask) via gunicorn on Cloud Run.
#
# Storage classes are wired before gunicorn starts.  Use sync_get / sync_set
# in your callbacks — they are safe to call from synchronous code.
import os

import $source_module as _user_module
$backend_imports
from skaal.runtime.local import LocalRuntime

# Wire Skaal storage before gunicorn forks workers.
LocalRuntime(
    _user_module.$app_var,
    backend_overrides={
$backend_overrides
    },
)

# WSGI callable — mounted via app.mount_wsgi("$wsgi_attribute")
# gunicorn is invoked in the Dockerfile CMD and imports this module as:
#   gunicorn main:application
application = _user_module.$wsgi_attribute
