"""
Generated by `skaal deploy`. Do not edit manually.
App: $app_name  Target: gcp-cloudrun
"""
import asyncio
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

import $source_module as _user_module

$backend_imports
from skaal.runtime.local import LocalRuntime

_runtime = LocalRuntime(
    _user_module.$app_var,
    host="0.0.0.0",
    port=int(os.environ.get("PORT", "8080")),
    backend_overrides={
$backend_overrides
    },
)

if __name__ == "__main__":
    asyncio.run(_runtime.serve())
