"""
Generated by `skaal deploy`. Do not edit manually.
App: $app_name  Target: gcp-cloudrun
"""
import asyncio
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

import $source_module as _user_module
from skaal.plan import PlanFile
from skaal.runtime.local import LocalRuntime

_plan = PlanFile.model_validate_json($plan_json_literal)

_runtime = LocalRuntime.from_plan(
    _user_module.$app_var,
    _plan,
    target="$target_name",
    host="0.0.0.0",
    port=int(os.environ.get("PORT", "8080")),
)

if __name__ == "__main__":
    asyncio.run(_runtime.serve())
