"""Alembic-driven DDL migrations for the relational tier.

State for each app lives at::

    .skaal/migrations/{app_name}/relational/{backend_label}/
        env.py
        script.py.mako
        alembic.ini
        versions/
            <revision_id>_<slug>.py

One subdirectory per *resolved relational backend*, so an app that pins one
SQLModel to SQLite and another to Postgres keeps two independent linear
histories.
"""

from __future__ import annotations

import asyncio
import io
import re
from contextlib import redirect_stdout
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from skaal.migrate.engine import MigrationKind, state_dir
from skaal.relational import get_backend, is_relational_model
from skaal.types.relational import (
    RelationalMigrationOp,
    RelationalMigrationPlan,
    RelationalMigrationStatus,
    RelationalMigrationStep,
    RelationalRevision,
)

_ENV_PY = '''\
"""Auto-generated by Skaal. Do not edit by hand — regenerate via skaal migrate."""

from __future__ import annotations

import asyncio

from alembic import context
from sqlalchemy.ext.asyncio import async_engine_from_config

config = context.config
target_metadata = config.attributes.get("target_metadata")
include_tables = config.attributes.get("include_tables")


def include_object(object_, name, type_, reflected, compare_to):
    if include_tables is None:
        return True
    if type_ == "table":
        return name in include_tables
    if type_ == "index":
        table = getattr(object_, "table", None)
        return table is None or table.name in include_tables
    return True


def _do_run_migrations(connection):
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_object=include_object,
        render_as_batch=connection.dialect.name == "sqlite",
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def _run_online():
    section = config.get_section(config.config_ini_section) or {}
    engine = async_engine_from_config(section, prefix="sqlalchemy.")
    async with engine.connect() as connection:
        await connection.run_sync(_do_run_migrations)
    await engine.dispose()


def _run_offline():
    url = config.get_main_option("sqlalchemy.url") or ""
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        render_as_batch=url.startswith("sqlite"),
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


if context.is_offline_mode():
    _run_offline()
else:
    asyncio.run(_run_online())
'''

_ALEMBIC_INI = """\
# Auto-generated by Skaal. Do not edit by hand.
[alembic]
script_location = {script_location}
sqlalchemy.url = {url}
prepend_sys_path = .
path_separator = os
file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d_%%(slug)s

[loggers]
keys = root,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
"""


@dataclass
class _BackendGroup:
    """One resolved relational backend and the models that resolve to it."""

    name: str
    backend: Any
    models: list[type] = field(default_factory=list)

    @property
    def table_names(self) -> set[str]:
        return {model.__tablename__ for model in self.models}

    def metadata(self) -> Any:
        from sqlmodel import SQLModel

        return SQLModel.metadata


def _backend_class_short(backend: Any) -> str:
    name = type(backend).__name__
    short = re.sub(r"Backend$", "", name).lower()
    return short or name.lower()


def _collect_groups(app: Any) -> list[_BackendGroup]:
    """Group registered relational SQLModels by *database*, not by backend instance.

    Multiple ``SqliteBackend(path=p, namespace=N)`` instances that share *p*
    represent the same physical database; each model just gets its own
    namespace for the KV facade. They must share one Alembic history.
    """
    groups: list[_BackendGroup] = []
    seen: dict[tuple[str, str], _BackendGroup] = {}
    for obj in app._collect_all().values():
        if not is_relational_model(obj):
            continue
        backend = get_backend(obj)
        base = _backend_class_short(backend)
        key = (base, _alembic_url(backend))
        group = seen.get(key)
        if group is None:
            existing = {g.name for g in groups}
            label = base
            counter = 2
            while label in existing:
                label = f"{base}_{counter}"
                counter += 1
            group = _BackendGroup(name=label, backend=backend)
            groups.append(group)
            seen[key] = group
        group.models.append(obj)
    return groups


def _select_groups(app: Any, backend_name: str | None) -> list[_BackendGroup]:
    groups = _collect_groups(app)
    if not groups:
        raise ValueError(f"No relational SQLModels registered on {app.name!r}.")
    if backend_name is None:
        return groups
    matched = [g for g in groups if g.name == backend_name]
    if not matched:
        available = ", ".join(sorted(g.name for g in groups))
        raise ValueError(f"No relational backend named {backend_name!r}. Available: {available}.")
    return matched


class RelationalMigrationStore:
    """The on-disk Alembic project for one ``(app, backend)`` pair."""

    def __init__(self, app_name: str, backend_label: str) -> None:
        self.app_name = app_name
        self.backend_label = backend_label
        self.root = state_dir(app_name, MigrationKind.RELATIONAL) / backend_label

    @property
    def versions_dir(self) -> Path:
        return self.root / "versions"

    @property
    def env_py(self) -> Path:
        return self.root / "env.py"

    @property
    def script_mako(self) -> Path:
        return self.root / "script.py.mako"

    @property
    def alembic_ini(self) -> Path:
        return self.root / "alembic.ini"

    def ensure(self, sqlalchemy_url: str) -> None:
        """Create or refresh the Alembic project files. Idempotent."""
        self.root.mkdir(parents=True, exist_ok=True)
        self.versions_dir.mkdir(exist_ok=True)
        if not self.env_py.exists():
            self.env_py.write_text(_ENV_PY)
        if not self.script_mako.exists():
            self.script_mako.write_text(_DEFAULT_SCRIPT_MAKO)
        # alembic.ini gets rewritten every time so a moved DB picks up the new url.
        self.alembic_ini.write_text(
            _ALEMBIC_INI.format(
                script_location=str(self.root.resolve()),
                url=sqlalchemy_url,
            )
        )


_DEFAULT_SCRIPT_MAKO = '''\
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
${imports if imports else ""}

revision: str = ${repr(up_revision)}
down_revision: Union[str, None] = ${repr(down_revision)}
branch_labels: Union[str, Sequence[str], None] = ${repr(branch_labels)}
depends_on: Union[str, Sequence[str], None] = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
'''


def _alembic_url(backend: Any) -> str:
    """Return a SQLAlchemy URL string for *backend*'s relational engine."""
    if hasattr(backend, "_sqlalchemy_url"):
        return backend._sqlalchemy_url()
    if hasattr(backend, "_sqlalchemy_dsn"):
        return backend._sqlalchemy_dsn()
    raise TypeError(f"{type(backend).__name__} does not expose a SQLAlchemy URL for migrations.")


def _build_config(group: _BackendGroup, app_name: str) -> Any:
    """Materialize the on-disk project and return a ready ``alembic.Config``."""
    from alembic.config import Config as AlembicConfig

    store = RelationalMigrationStore(app_name, group.name)
    store.ensure(_alembic_url(group.backend))

    cfg = AlembicConfig(str(store.alembic_ini))
    cfg.set_main_option("script_location", str(store.root.resolve()))
    cfg.attributes["target_metadata"] = group.metadata()
    cfg.attributes["include_tables"] = group.table_names
    return cfg


# ── public API ────────────────────────────────────────────────────────────────


async def auto_upgrade_existing(app: Any) -> dict[str, RelationalMigrationStatus]:
    """Run ``upgrade head`` only for backends that already have a versions/ dir.

    Used by runtime startup so apps that have not yet created any migrations
    keep falling back to ``ensure_schema``'s ``create_all`` path.
    """
    groups = _collect_groups(app)
    results: dict[str, RelationalMigrationStatus] = {}
    for group in groups:
        store = RelationalMigrationStore(app.name, group.name)
        if not store.versions_dir.exists():
            continue
        if not any(store.versions_dir.glob("*.py")):
            continue
        await asyncio.to_thread(_run_upgrade, group, app.name, "head")
        results[group.name] = await asyncio.to_thread(_build_status, group, app.name)
    return results


async def autogenerate(
    app: Any,
    *,
    message: str,
    backend_name: str | None = None,
) -> dict[str, RelationalRevision | None]:
    """Generate one autodetect revision per backend. Returns ``None`` for backends
    where no DDL changes were detected.
    """
    groups = _select_groups(app, backend_name)
    results: dict[str, RelationalRevision | None] = {}
    for group in groups:
        results[group.name] = await asyncio.to_thread(_autogenerate_one, group, app.name, message)
    return results


def _autogenerate_one(
    group: _BackendGroup, app_name: str, message: str
) -> RelationalRevision | None:
    from alembic import command
    from alembic.script import ScriptDirectory

    cfg = _build_config(group, app_name)
    script = command.revision(cfg, message=message, autogenerate=True)
    if script is None:
        return None

    rev = ScriptDirectory.from_config(cfg).get_revision(script.revision)
    return RelationalRevision(
        revision_id=rev.revision,
        down_revision=rev.down_revision if isinstance(rev.down_revision, str) else None,
        message=rev.doc or "",
        created_at=datetime.now(timezone.utc),
        is_head=True,
        is_applied=False,
    )


async def upgrade(
    app: Any,
    *,
    target: str = "head",
    backend_name: str | None = None,
) -> dict[str, RelationalMigrationStatus]:
    """Apply pending migrations up to *target* on every selected backend."""
    groups = _select_groups(app, backend_name)
    results: dict[str, RelationalMigrationStatus] = {}
    for group in groups:
        await asyncio.to_thread(_run_upgrade, group, app.name, target)
        results[group.name] = await asyncio.to_thread(_build_status, group, app.name)
    return results


def _run_upgrade(group: _BackendGroup, app_name: str, target: str) -> None:
    from alembic import command

    cfg = _build_config(group, app_name)
    command.upgrade(cfg, target)


async def downgrade(
    app: Any,
    *,
    target: str,
    backend_name: str | None = None,
) -> dict[str, RelationalMigrationStatus]:
    """Roll selected backends back to *target*."""
    groups = _select_groups(app, backend_name)
    results: dict[str, RelationalMigrationStatus] = {}
    for group in groups:
        await asyncio.to_thread(_run_downgrade, group, app.name, target)
        results[group.name] = await asyncio.to_thread(_build_status, group, app.name)
    return results


def _run_downgrade(group: _BackendGroup, app_name: str, target: str) -> None:
    from alembic import command

    cfg = _build_config(group, app_name)
    command.downgrade(cfg, target)


async def plan_upgrade(
    app: Any,
    *,
    target: str = "head",
    backend_name: str | None = None,
) -> dict[str, RelationalMigrationPlan]:
    """Render the SQL of an upgrade without applying it (offline mode)."""
    groups = _select_groups(app, backend_name)
    results: dict[str, RelationalMigrationPlan] = {}
    for group in groups:
        results[group.name] = await asyncio.to_thread(
            _render_plan, group, app.name, "upgrade", target
        )
    return results


async def plan_downgrade(
    app: Any,
    *,
    target: str,
    backend_name: str | None = None,
) -> dict[str, RelationalMigrationPlan]:
    """Render the SQL of a downgrade without applying it (offline mode)."""
    groups = _select_groups(app, backend_name)
    results: dict[str, RelationalMigrationPlan] = {}
    for group in groups:
        results[group.name] = await asyncio.to_thread(
            _render_plan, group, app.name, "downgrade", target
        )
    return results


def _render_plan(
    group: _BackendGroup, app_name: str, direction: str, target: str
) -> RelationalMigrationPlan:
    from alembic import command

    cfg = _build_config(group, app_name)
    current_rev = _read_current(group)

    buf = io.StringIO()
    with redirect_stdout(buf):
        if direction == "upgrade":
            from_arg = f"{current_rev or 'base'}:{target}"
            command.upgrade(cfg, from_arg, sql=True)
        else:
            from_arg = f"{current_rev or 'head'}:{target}"
            command.downgrade(cfg, from_arg, sql=True)

    sql = buf.getvalue()
    steps = _parse_sql_steps(sql)
    return RelationalMigrationPlan(
        backend_name=group.name,
        direction=direction,  # type: ignore[arg-type]
        from_revision=current_rev,
        to_revision=target,
        steps=steps,
        is_empty=not steps,
    )


async def current(
    app: Any,
    *,
    backend_name: str | None = None,
) -> dict[str, RelationalMigrationStatus]:
    """Return the live current/head/applied/pending state per backend."""
    groups = _select_groups(app, backend_name)
    return {group.name: await asyncio.to_thread(_build_status, group, app.name) for group in groups}


async def history(
    app: Any,
    *,
    backend_name: str | None = None,
) -> dict[str, list[RelationalRevision]]:
    """Return every revision in ``versions/`` per backend, newest first."""
    groups = _select_groups(app, backend_name)
    return {
        group.name: await asyncio.to_thread(_list_revisions, group, app.name) for group in groups
    }


async def stamp(
    app: Any,
    *,
    target: str,
    backend_name: str | None = None,
) -> dict[str, RelationalMigrationStatus]:
    """Stamp the alembic_version table to *target* without running migrations."""
    groups = _select_groups(app, backend_name)
    results: dict[str, RelationalMigrationStatus] = {}
    for group in groups:
        await asyncio.to_thread(_run_stamp, group, app.name, target)
        results[group.name] = await asyncio.to_thread(_build_status, group, app.name)
    return results


def _run_stamp(group: _BackendGroup, app_name: str, target: str) -> None:
    from alembic import command

    cfg = _build_config(group, app_name)
    command.stamp(cfg, target)


async def check(
    app: Any,
    *,
    backend_name: str | None = None,
) -> dict[str, RelationalMigrationPlan]:
    """Detect drift between the live schema and the registered SQLModels.

    Each plan's ``is_empty`` flag is ``True`` iff no DDL would be emitted.
    """
    groups = _select_groups(app, backend_name)
    results: dict[str, RelationalMigrationPlan] = {}
    for group in groups:
        results[group.name] = await asyncio.to_thread(_check_one, group)
    return results


def _check_one(group: _BackendGroup) -> RelationalMigrationPlan:
    from alembic.autogenerate import compare_metadata
    from alembic.runtime.migration import MigrationContext
    from sqlalchemy import create_engine

    current_rev = _read_current(group)
    sync_url = _sync_url_from(_alembic_url(group.backend))

    engine = create_engine(sync_url)
    try:
        with engine.connect() as connection:
            ctx = MigrationContext.configure(
                connection=connection,
                opts={
                    "target_metadata": group.metadata(),
                    "include_object": _include_object_for(group.table_names),
                    "compare_type": True,
                },
            )
            diff = compare_metadata(ctx, group.metadata())
    finally:
        engine.dispose()

    steps = [_step_from_diff(entry) for entry in diff]
    return RelationalMigrationPlan(
        backend_name=group.name,
        direction="upgrade",
        from_revision=current_rev,
        to_revision="head",
        steps=steps,
        is_empty=not steps,
    )


def _include_object_for(table_names: set[str]):
    def _include(object_, name, type_, reflected, compare_to):
        if type_ == "table":
            return name in table_names
        if type_ == "index":
            table = getattr(object_, "table", None)
            return table is None or table.name in table_names
        return True

    return _include


def _sync_url_from(async_url: str) -> str:
    """Convert an async SQLAlchemy URL to its sync equivalent for ``check``."""
    return async_url.replace("+aiosqlite", "").replace("+asyncpg", "").replace("+aiopg", "")


_DIFF_OP_MAP: dict[str, RelationalMigrationOp] = {
    "add_table": RelationalMigrationOp.CREATE_TABLE,
    "remove_table": RelationalMigrationOp.DROP_TABLE,
    "add_column": RelationalMigrationOp.ADD_COLUMN,
    "remove_column": RelationalMigrationOp.DROP_COLUMN,
    "modify_default": RelationalMigrationOp.ALTER_COLUMN,
    "modify_nullable": RelationalMigrationOp.ALTER_COLUMN,
    "modify_type": RelationalMigrationOp.ALTER_COLUMN,
    "add_index": RelationalMigrationOp.CREATE_INDEX,
    "remove_index": RelationalMigrationOp.DROP_INDEX,
}


def _step_from_diff(entry: Any) -> RelationalMigrationStep:
    if isinstance(entry, list):
        # Column-level diff: list of (op_name, schema, table, column, ...) tuples.
        first = entry[0]
        op_name = first[0]
        op = _DIFF_OP_MAP.get(op_name, RelationalMigrationOp.OTHER)
        table = first[2] if len(first) > 2 else None
        detail = " / ".join(str(t) for t in first[3:])
        return RelationalMigrationStep(op=op, table=table, detail=detail, sql="")

    op_name = entry[0]
    op = _DIFF_OP_MAP.get(op_name, RelationalMigrationOp.OTHER)
    target = entry[1] if len(entry) > 1 else None
    table = getattr(target, "name", None) if target is not None else None
    detail = repr(target) if target is not None else op_name
    return RelationalMigrationStep(op=op, table=table, detail=detail, sql="")


_SQL_OP_PATTERNS: list[tuple[re.Pattern[str], RelationalMigrationOp]] = [
    (re.compile(r"^\s*CREATE\s+TABLE\s+", re.IGNORECASE), RelationalMigrationOp.CREATE_TABLE),
    (re.compile(r"^\s*DROP\s+TABLE\s+", re.IGNORECASE), RelationalMigrationOp.DROP_TABLE),
    (
        re.compile(r"^\s*ALTER\s+TABLE\s+\S+\s+ADD\s+", re.IGNORECASE),
        RelationalMigrationOp.ADD_COLUMN,
    ),
    (
        re.compile(r"^\s*ALTER\s+TABLE\s+\S+\s+DROP\s+COLUMN", re.IGNORECASE),
        RelationalMigrationOp.DROP_COLUMN,
    ),
    (
        re.compile(r"^\s*ALTER\s+TABLE\s+\S+\s+ALTER\s+", re.IGNORECASE),
        RelationalMigrationOp.ALTER_COLUMN,
    ),
    (
        re.compile(r"^\s*CREATE\s+(UNIQUE\s+)?INDEX\s+", re.IGNORECASE),
        RelationalMigrationOp.CREATE_INDEX,
    ),
    (re.compile(r"^\s*DROP\s+INDEX\s+", re.IGNORECASE), RelationalMigrationOp.DROP_INDEX),
]

_TABLE_NAME_RE = re.compile(
    r"\b(?:TABLE|INDEX)\s+(?:IF\s+(?:NOT\s+)?EXISTS\s+)?(\S+)", re.IGNORECASE
)


def _parse_sql_steps(sql: str) -> list[RelationalMigrationStep]:
    """Split a multi-statement SQL string into one ``RelationalMigrationStep`` per statement."""
    steps: list[RelationalMigrationStep] = []
    for raw in sql.split(";"):
        stmt = raw.strip()
        if (
            not stmt
            or stmt.startswith("--")
            or stmt.upper().startswith("BEGIN")
            or stmt.upper().startswith("COMMIT")
        ):
            continue
        if "alembic_version" in stmt.lower():
            continue
        op = _classify_sql(stmt)
        table = _extract_table_name(stmt)
        steps.append(
            RelationalMigrationStep(
                op=op, table=table, detail=stmt.split("\n", 1)[0], sql=stmt + ";"
            )
        )
    return steps


def _classify_sql(stmt: str) -> RelationalMigrationOp:
    for pattern, op in _SQL_OP_PATTERNS:
        if pattern.match(stmt):
            return op
    return RelationalMigrationOp.OTHER


def _extract_table_name(stmt: str) -> str | None:
    match = _TABLE_NAME_RE.search(stmt)
    if match is None:
        return None
    return match.group(1).strip("\"`' ")


def _read_current(group: _BackendGroup) -> str | None:
    """Read the current revision id from the live database, if any."""
    from alembic.runtime.migration import MigrationContext
    from sqlalchemy import create_engine

    sync_url = _sync_url_from(_alembic_url(group.backend))
    engine = create_engine(sync_url)
    try:
        with engine.connect() as connection:
            return MigrationContext.configure(connection=connection).get_current_revision()
    finally:
        engine.dispose()


def _list_revisions(group: _BackendGroup, app_name: str) -> list[RelationalRevision]:
    from alembic.script import ScriptDirectory

    cfg = _build_config(group, app_name)
    script = ScriptDirectory.from_config(cfg)
    head_ids = set(script.get_heads())
    current_rev = _read_current(group)

    revisions: list[RelationalRevision] = []
    for rev in script.walk_revisions():
        revisions.append(
            RelationalRevision(
                revision_id=rev.revision,
                down_revision=rev.down_revision if isinstance(rev.down_revision, str) else None,
                message=rev.doc or "",
                created_at=_revision_created_at(script, rev.revision),
                is_head=rev.revision in head_ids,
                is_applied=_is_applied(rev.revision, current_rev, script),
            )
        )
    return revisions


def _revision_created_at(script: Any, revision_id: str) -> datetime:
    """Best-effort revision file mtime — Alembic does not store created_at."""
    rev = script.get_revision(revision_id)
    path = Path(rev.path) if rev.path else None
    if path is not None and path.exists():
        return datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)
    return datetime.now(timezone.utc)


def _is_applied(revision_id: str, current_rev: str | None, script: Any) -> bool:
    if current_rev is None:
        return False
    if revision_id == current_rev:
        return True
    # A revision is "applied" if it is an ancestor of the current revision.
    for ancestor in script.iterate_revisions(current_rev, "base"):
        if ancestor.revision == revision_id:
            return True
    return False


def _build_status(group: _BackendGroup, app_name: str) -> RelationalMigrationStatus:
    from alembic.script import ScriptDirectory

    cfg = _build_config(group, app_name)
    script = ScriptDirectory.from_config(cfg)
    head_ids = script.get_heads()
    head = head_ids[0] if head_ids else None
    current_rev = _read_current(group)

    all_revs = _list_revisions(group, app_name)
    applied = [r for r in all_revs if r.is_applied]
    pending = [r for r in all_revs if not r.is_applied]
    return RelationalMigrationStatus(
        backend_name=group.name,
        current_revision=current_rev,
        head_revision=head,
        pending=pending,
        applied=applied,
    )


__all__ = [
    "RelationalMigrationStore",
    "auto_upgrade_existing",
    "autogenerate",
    "check",
    "current",
    "downgrade",
    "history",
    "plan_downgrade",
    "plan_upgrade",
    "stamp",
    "upgrade",
]
