# Generated by `skaal build --target local` (async mode).
# Serves the user's async app via uvicorn in Docker Compose.
#
# Storage classes are wired before uvicorn starts.  Use async_get / async_set
# in your callbacks.
import importlib
import os

_user_module = importlib.import_module("$source_module")
$backend_imports
from skaal.runtime.local import LocalRuntime

# Wire Skaal storage before server starts.
LocalRuntime(
    _user_module.$app_var,
    backend_overrides={
$backend_overrides
    },
)

# ASGI app — directly served by uvicorn
app = _user_module.$app_var
