# Generated by `skaal build --target local` (async mode).
# Serves the user's async app via gunicorn + uvicorn workers in Docker Compose.
#
# Storage classes are wired before the server starts.  Use async_get / async_set
# in your function bodies.
import importlib

_user_module = importlib.import_module("$source_module")
from skaal.plan import PlanFile
from skaal.runtime.local import LocalRuntime

_plan = PlanFile.model_validate_json($plan_json_literal)

# Wire Skaal storage and build the ASGI app.
# LocalRuntime patches every @app.storage() class from the resolved plan.
_runtime = LocalRuntime.from_plan(
    _user_module.$app_var,
    _plan,
    target="$target_name",
)

# ASGI callable — gunicorn is invoked in the Dockerfile CMD as:
#   gunicorn -k uvicorn.workers.UvicornWorker main:application
application = _runtime.build_asgi()
