# Generated by `skaal build --target local` (WSGI mode).
# Serves the user's WSGI app (e.g. Dash/Flask) via gunicorn in Docker Compose.
#
# Storage classes are wired before gunicorn starts.  Use sync_get / sync_set
# in your callbacks — they are safe to call from synchronous code.
import importlib
import os

_user_module = importlib.import_module("$source_module")
from skaal.plan import PlanFile
from skaal.runtime.local import LocalRuntime

_plan = PlanFile.model_validate_json($plan_json_literal)

# Wire Skaal storage before gunicorn forks workers, then start the
# background scheduler so @app.schedule() functions run in Docker too.
_runtime = LocalRuntime.from_plan(
    _user_module.$app_var,
    _plan,
    target="$target_name",
)
# Starts APScheduler in a daemon thread; each firing is printed to stdout
# so it appears in `docker logs`.  No-ops if apscheduler is not installed.
_runtime.start_background_scheduler()

# WSGI callable — mounted via app.mount_wsgi("$wsgi_attribute")
# gunicorn is invoked in the Dockerfile CMD and imports this module as:
#   gunicorn main:application
application = _user_module.$wsgi_attribute
