"""
Generated by `skaal deploy`. Do not edit manually.
App: $app_name  Target: aws-lambda
"""
import asyncio
import base64
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

import $source_module as _user_module

$backend_imports
from skaal.runtime.local import LocalRuntime

_runtime = LocalRuntime(
    _user_module.$app_var,
    backend_overrides={
$backend_overrides
    },
)


def handler(event, context):
    method = event.get("requestContext", {}).get("http", {}).get("method", "POST")
    path = event.get("rawPath", "/")
    raw_body = event.get("body") or ""
    if event.get("isBase64Encoded"):
        body = base64.b64decode(raw_body)
    else:
        body = raw_body.encode() if isinstance(raw_body, str) else raw_body
    result, status = asyncio.run(_runtime._dispatch(method, path, body))
    return {
        "statusCode": status,
        "headers": {"Content-Type": "application/json"},
        "body": json.dumps(result, default=str),
    }
