# Generated by `skaal deploy --target aws` (WSGI mode).
# Serves the user's WSGI app (e.g. Dash/Flask) via mangum on AWS Lambda.
#
# Storage classes are wired at cold-start.  Use sync_get / sync_set in
# your callbacks — they are safe to call from synchronous code.
import os

import $source_module as _user_module
from skaal.plan import PlanFile
from skaal.runtime.local import LocalRuntime

_plan = PlanFile.model_validate_json($plan_json_literal)

# Wire Skaal storage at cold-start.
LocalRuntime.from_plan(
    _user_module.$app_var,
    _plan,
    target="$target_name",
)

# WSGI callable — mounted via app.mount_wsgi("$wsgi_attribute")
_wsgi_app = _user_module.$wsgi_attribute

# mangum adapts WSGI to the Lambda event/context interface.
from mangum import Mangum  # noqa: E402
handler = Mangum(_wsgi_app, lifespan="off")
