"""AWS Lambda artifact generator — generates deployable Lambda + Pulumi stack."""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from skaal.plan import PlanFile


def generate_artifacts(
    app: Any,
    plan: "PlanFile",
    output_dir: Path,
    source_module: str,
    app_var: str = "app",
) -> list[Path]:
    """
    Generate Lambda + Pulumi deployment artifacts.

    Args:
        app:           The Skaal App instance.
        plan:          The solved PlanFile (plan.skaal.lock).
        output_dir:    Directory to write files into.
        source_module: Python module path, e.g. "examples.counter".
        app_var:       Variable name of the app in the module, e.g. "app".

    Returns:
        List of generated file paths.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    pulumi_dir = output_dir / "pulumi"
    pulumi_dir.mkdir(parents=True, exist_ok=True)

    generated: list[Path] = []

    # Build wiring code: one patch_storage_class() call per storage spec
    wiring_lines: list[str] = []
    for qname, spec in plan.storage.items():
        # Derive the class name from the qualified name (last component)
        class_name = qname.split(".")[-1]
        # Env var name: SKIM_TABLE_{CLASS_NAME_UPPER}
        env_var = f"SKIM_TABLE_{class_name.upper()}"
        wiring_lines.append(
            f'patch_storage_class(_user_module.{class_name}, '
            f'DynamoBackend(os.environ["{env_var}"]))'
        )
    wiring_code = "\n".join(wiring_lines) if wiring_lines else "# no storage classes"

    # ── handler.py ────────────────────────────────────────────────────────
    handler_content = textwrap.dedent(f"""\
        \"\"\"
        Generated by `skaal deploy`. Do not edit manually.
        App: {app.name}  Target: aws-lambda
        \"\"\"
        import asyncio
        import json
        import os
        import sys

        sys.path.insert(0, os.path.dirname(__file__))

        import {source_module} as _user_module  # noqa: E402
        _app = _user_module.{app_var}

        from skaal.backends.dynamodb_backend import DynamoBackend
        from skaal.backends.local_backend import patch_storage_class
        from skaal.runtime.local import LocalRuntime

        # Wire backends from plan.skaal.lock
        {wiring_code}

        _runtime = LocalRuntime(_app)


        def handler(event, context):
            method = event.get("requestContext", {{}}).get("http", {{}}).get("method", "POST")
            path = event.get("rawPath", "/")
            raw_body = event.get("body") or ""
            if event.get("isBase64Encoded"):
                import base64
                body = base64.b64decode(raw_body)
            else:
                body = raw_body.encode() if isinstance(raw_body, str) else raw_body
            result, status = asyncio.run(_runtime._dispatch(method, path, body))
            return {{
                "statusCode": status,
                "headers": {{"Content-Type": "application/json"}},
                "body": json.dumps(result, default=str),
            }}
    """)

    handler_path = output_dir / "handler.py"
    handler_path.write_text(handler_content)
    generated.append(handler_path)

    # ── pulumi/__main__.py ────────────────────────────────────────────────
    table_resources: list[str] = []
    table_names: list[str] = []
    env_vars_lines: list[str] = []

    for qname, spec in plan.storage.items():
        class_name = qname.split(".")[-1]
        resource_var = f"table_{class_name.lower()}"
        table_name_var = f"table_name_{class_name.lower()}"
        env_key = f"SKIM_TABLE_{class_name.upper()}"

        table_resources.append(
            f'{table_name_var} = f"{{stack_name}}-{class_name.lower()}"\n'
            f'{resource_var} = aws.dynamodb.Table(\n'
            f'    "{class_name.lower()}-table",\n'
            f'    name={table_name_var},\n'
            f'    hash_key="pk",\n'
            f'    billing_mode="PAY_PER_REQUEST",\n'
            f'    attributes=[aws.dynamodb.TableAttributeArgs(name="pk", type="S")],\n'
            f'    tags={{"skim-app": app_name, "skim-storage": "{qname}"}},\n'
            f')\n'
        )
        table_names.append(f'    "{class_name.lower()}": {resource_var}.name')
        env_vars_lines.append(f'    "{env_key}": {resource_var}.name,')

    table_resources_str = "\n".join(table_resources)
    table_names_str = ",\n".join(table_names)
    env_vars_str = "\n".join(env_vars_lines)

    # Build Pulumi main without leading indentation issues
    pulumi_lines = [
        '"""',
        f"Pulumi stack generated by `skaal deploy`.",
        f"App: {app.name}  Target: aws-lambda",
        "Do not edit manually — regenerate with `skaal deploy`.",
        '"""',
        "import pulumi",
        "import pulumi_aws as aws",
        "",
        "config = pulumi.Config()",
        "stack_name = pulumi.get_stack()",
        f'app_name = "{app.name}"',
        "",
        "# ── DynamoDB Tables ──────────────────────────────────────────────",
        table_resources_str,
        "# ── IAM Role for Lambda ──────────────────────────────────────────",
        "assume_role_policy = {",
        '    "Version": "2012-10-17",',
        '    "Statement": [{',
        '        "Effect": "Allow",',
        '        "Principal": {"Service": "lambda.amazonaws.com"},',
        '        "Action": "sts:AssumeRole",',
        "    }],",
        "}",
        "",
        "lambda_role = aws.iam.Role(",
        '    "skim-lambda-role",',
        f'    name=f"{{stack_name}}-{app.name}-role",',
        "    assume_role_policy=__import__('json').dumps(assume_role_policy),",
        ")",
        "",
        "# Attach basic Lambda execution policy",
        "aws.iam.RolePolicyAttachment(",
        '    "lambda-basic-exec",',
        "    role=lambda_role.name,",
        '    policy_arn="arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",',
        ")",
        "",
        "# DynamoDB access policy",
        "dynamodb_policy_doc = {",
        '    "Version": "2012-10-17",',
        '    "Statement": [{',
        '        "Effect": "Allow",',
        '        "Action": [',
        '            "dynamodb:GetItem",',
        '            "dynamodb:PutItem",',
        '            "dynamodb:DeleteItem",',
        '            "dynamodb:Scan",',
        '            "dynamodb:Query",',
        "        ],",
        '        "Resource": "*",',
        "    }],",
        "}",
        "dynamodb_policy = aws.iam.Policy(",
        '    "skim-dynamodb-policy",',
        f'    name=f"{{stack_name}}-{app.name}-dynamodb",',
        "    policy=__import__('json').dumps(dynamodb_policy_doc),",
        ")",
        "",
        "aws.iam.RolePolicyAttachment(",
        '    "lambda-dynamodb-attach",',
        "    role=lambda_role.name,",
        "    policy_arn=dynamodb_policy.arn,",
        ")",
        "",
        "# ── Lambda Function ──────────────────────────────────────────────",
        "lambda_env_vars = {",
        env_vars_str,
        "}",
        "",
        "lambda_fn = aws.lambda_.Function(",
        '    "skim-lambda",',
        f'    name=f"{{stack_name}}-{app.name}",',
        '    runtime="python3.11",',
        '    handler="handler.handler",',
        "    role=lambda_role.arn,",
        '    code=pulumi.FileArchive("./lambda_package"),',
        "    timeout=30,",
        "    memory_size=256,",
        "    environment=aws.lambda_.FunctionEnvironmentArgs(",
        "        variables=lambda_env_vars,",
        "    ),",
        ")",
        "",
        "# ── HTTP API Gateway v2 ───────────────────────────────────────────",
        "api = aws.apigatewayv2.Api(",
        '    "skim-api",',
        f'    name=f"{{stack_name}}-{app.name}-api",',
        '    protocol_type="HTTP",',
        ")",
        "",
        "lambda_permission = aws.lambda_.Permission(",
        '    "api-invoke-lambda",',
        '    action="lambda:InvokeFunction",',
        "    function=lambda_fn.arn,",
        '    principal="apigateway.amazonaws.com",',
        "    source_arn=api.execution_arn.apply(lambda arn: f\"{arn}/*/*\"),",
        ")",
        "",
        "integration = aws.apigatewayv2.Integration(",
        '    "lambda-integration",',
        "    api_id=api.id,",
        '    integration_type="AWS_PROXY",',
        "    integration_uri=lambda_fn.invoke_arn,",
        '    payload_format_version="2.0",',
        ")",
        "",
        "route = aws.apigatewayv2.Route(",
        '    "default-route",',
        "    api_id=api.id,",
        '    route_key="$default",',
        "    target=integration.id.apply(lambda i: f\"integrations/{i}\"),",
        ")",
        "",
        "stage = aws.apigatewayv2.Stage(",
        '    "default-stage",',
        "    api_id=api.id,",
        '    name="$default",',
        "    auto_deploy=True,",
        "    opts=pulumi.ResourceOptions(depends_on=[route]),",
        ")",
        "",
        "# ── Exports ───────────────────────────────────────────────────────",
        'pulumi.export("api_url", stage.invoke_url)',
        'pulumi.export("lambda_arn", lambda_fn.arn)',
        "pulumi.export(\"dynamodb_tables\", {",
        table_names_str + ",",
        "})",
    ]
    pulumi_main_content = "\n".join(pulumi_lines) + "\n"

    pulumi_main_path = pulumi_dir / "__main__.py"
    pulumi_main_path.write_text(pulumi_main_content)
    generated.append(pulumi_main_path)

    # ── pulumi/Pulumi.yaml ────────────────────────────────────────────────
    pulumi_yaml_content = textwrap.dedent(f"""\
        name: skim-{app.name}
        runtime: python
        description: Generated by skim deploy
    """)
    pulumi_yaml_path = pulumi_dir / "Pulumi.yaml"
    pulumi_yaml_path.write_text(pulumi_yaml_content)
    generated.append(pulumi_yaml_path)

    # ── requirements.txt ─────────────────────────────────────────────────
    requirements_content = textwrap.dedent("""\
        boto3>=1.34
    """)
    requirements_path = output_dir / "requirements.txt"
    requirements_path.write_text(requirements_content)
    generated.append(requirements_path)

    # ── README.md ────────────────────────────────────────────────────────
    resource_list = []
    for qname, spec in plan.storage.items():
        class_name = qname.split(".")[-1]
        resource_list.append(f"- DynamoDB table: `{class_name.lower()}` (backend: {spec.backend})")
    resource_list.append(f"- Lambda function: `{app.name}`")
    resource_list.append("- HTTP API Gateway v2")
    resource_list_str = "\n".join(resource_list)

    readme_content = textwrap.dedent(f"""\
        # Deploy {app.name} to AWS

        Generated by `skaal deploy`.

        ## Prerequisites
        - AWS credentials configured (`aws configure` or environment variables)
        - Pulumi CLI installed (`pip install pulumi pulumi-aws`)

        ## Deploy

        ```bash
        # 1. Package the Lambda function
        pip install -r requirements.txt -t lambda_package/
        cp handler.py lambda_package/
        cp -r ../skim lambda_package/skim  # bundle skim runtime
        cp -r ../{source_module.split('.')[0]} lambda_package/  # bundle your app

        # 2. Deploy infrastructure
        cd pulumi
        pip install pulumi pulumi-aws
        pulumi stack init dev
        pulumi config set aws:region us-east-1
        pulumi up
        ```

        ## Resources created

        {resource_list_str}
    """)

    readme_path = output_dir / "README.md"
    readme_path.write_text(readme_content)
    generated.append(readme_path)

    return generated
