"""GCP Cloud Run artifact generator — generates deployable Cloud Run + Pulumi stack."""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from skaal.plan import PlanFile

# Map catalog backend names to (backend_class, env_var_prefix, import_path)
_BACKEND_MAP: dict[str, tuple[str, str, str]] = {
    "firestore": (
        "FirestoreBackend",
        "SKAAL_COLLECTION",
        "skaal.backends.firestore_backend",
    ),
    "cloud-sql-postgres": (
        "PostgresBackend",
        "SKAAL_DB_DSN",
        "skaal.backends.postgres_backend",
    ),
    "memorystore-redis": (
        "RedisBackend",
        "SKAAL_REDIS_URL",
        "skaal.backends.redis_backend",
    ),
}

# Which backend requires VPC (Cloud SQL via private IP, Memorystore)
_REQUIRES_VPC = {"cloud-sql-postgres", "memorystore-redis"}


def _backend_info(backend_name: str) -> tuple[str, str, str]:
    """Return (class_name, env_var_prefix, import_path) for a catalog backend name."""
    if backend_name in _BACKEND_MAP:
        return _BACKEND_MAP[backend_name]
    # Default fallback: Firestore
    return _BACKEND_MAP["firestore"]


def generate_artifacts(
    app: Any,
    plan: "PlanFile",
    output_dir: Path,
    source_module: str,
    app_var: str = "app",
    region: str = "us-central1",
) -> list[Path]:
    """
    Generate Cloud Run + Pulumi deployment artifacts.

    Args:
        app:           The Skaal App instance.
        plan:          The solved PlanFile (plan.skaal.lock).
        output_dir:    Directory to write files into.
        source_module: Python module path, e.g. "examples.counter".
        app_var:       Variable name of the app in the module, e.g. "app".
        region:        GCP region, e.g. "us-central1".

    Returns:
        List of generated file paths.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    pulumi_dir = output_dir / "pulumi"
    pulumi_dir.mkdir(parents=True, exist_ok=True)

    generated: list[Path] = []

    # ── Build per-storage wiring ──────────────────────────────────────────
    imports_seen: set[str] = set()
    import_lines: list[str] = []
    wiring_lines: list[str] = []
    env_var_names: list[str] = []  # for Dockerfile ENV doc

    for qname, spec in plan.storage.items():
        class_name = qname.split(".")[-1]
        backend_name = spec.backend
        cls, env_prefix, import_path = _backend_info(backend_name)
        env_var = f"{env_prefix}_{class_name.upper()}"
        env_var_names.append(env_var)

        if import_path not in imports_seen:
            imports_seen.add(import_path)
            mod_short = import_path.split(".")[-1]
            import_lines.append(f"from {import_path} import {cls} as _{mod_short}_{cls}")

        if backend_name == "firestore":
            wiring_lines.append(
                f'patch_storage_class(_user_module.{class_name}, '
                f'_firestore_backend_FirestoreBackend(os.environ["{env_var}"]))'
            )
        elif backend_name == "cloud-sql-postgres":
            wiring_lines.append(
                f'patch_storage_class(_user_module.{class_name}, '
                f'_postgres_backend_PostgresBackend(os.environ["{env_var}"], '
                f'namespace="{class_name}"))'
            )
        elif backend_name == "memorystore-redis":
            wiring_lines.append(
                f'patch_storage_class(_user_module.{class_name}, '
                f'_redis_backend_RedisBackend(os.environ["{env_var}"], '
                f'namespace="{class_name}"))'
            )
        else:
            wiring_lines.append(
                f'patch_storage_class(_user_module.{class_name}, '
                f'_{import_path.split(".")[-1]}_{cls}(os.environ["{env_var}"]))'
            )

    imports_code = "\n".join(import_lines) if import_lines else ""
    wiring_code = "\n".join(wiring_lines) if wiring_lines else "# no storage classes"

    # ── main.py (Cloud Run entry point) ────────────────────────────────────
    main_content = textwrap.dedent(f"""\
        \"\"\"
        Generated by `skaal deploy`. Do not edit manually.
        App: {app.name}  Target: gcp-cloudrun
        \"\"\"
        import asyncio
        import json
        import os
        import sys

        sys.path.insert(0, os.path.dirname(__file__))

        import {source_module} as _user_module  # noqa: E402
        _app = _user_module.{app_var}

        {imports_code}
        from skaal.backends.local_backend import patch_storage_class
        from skaal.runtime.local import LocalRuntime

        # Wire backends resolved from plan.skaal.lock
        {wiring_code}

        _runtime = LocalRuntime(_app)

        # ── HTTP server (uvicorn/gunicorn compatible ASGI app) ─────────────
        from skaal.runtime.local import _make_asgi_app  # noqa: E402

        asgi_app = _make_asgi_app(_runtime)

        if __name__ == "__main__":
            import uvicorn
            port = int(os.environ.get("PORT", "8080"))
            uvicorn.run(asgi_app, host="0.0.0.0", port=port)
    """)

    main_path = output_dir / "main.py"
    main_path.write_text(main_content)
    generated.append(main_path)

    # ── Dockerfile ─────────────────────────────────────────────────────────
    dockerfile_content = textwrap.dedent(f"""\
        # Generated by `skaal deploy`. Do not edit manually.
        FROM python:3.11-slim

        WORKDIR /app

        COPY requirements.txt .
        RUN pip install --no-cache-dir -r requirements.txt

        COPY . .

        ENV PORT=8080
        EXPOSE 8080

        CMD ["python", "main.py"]
    """)

    dockerfile_path = output_dir / "Dockerfile"
    dockerfile_path.write_text(dockerfile_content)
    generated.append(dockerfile_path)

    # ── requirements.txt ───────────────────────────────────────────────────
    requirements_lines = ["skaal", "uvicorn>=0.29", "google-cloud-firestore>=2.16"]
    # Add Cloud SQL / Redis deps if needed
    for qname, spec in plan.storage.items():
        if spec.backend == "cloud-sql-postgres":
            requirements_lines.append("asyncpg>=0.29")
            requirements_lines.append("cloud-sql-python-connector[asyncpg]>=1.9")
        elif spec.backend == "memorystore-redis":
            requirements_lines.append("redis>=5.0")

    requirements_content = "\n".join(dict.fromkeys(requirements_lines)) + "\n"
    requirements_path = output_dir / "requirements.txt"
    requirements_path.write_text(requirements_content)
    generated.append(requirements_path)

    # ── pulumi/__main__.py ──────────────────────────────────────────────────
    # Build per-storage Pulumi resource stanzas
    storage_resources: list[str] = []
    env_vars_pulumi: list[str] = []
    needs_vpc = any(spec.backend in _REQUIRES_VPC for _, spec in plan.storage.items())

    for qname, spec in plan.storage.items():
        class_name = qname.split(".")[-1]
        backend_name = spec.backend
        _, env_prefix, _ = _backend_info(backend_name)
        env_var = f"{env_prefix}_{class_name.upper()}"

        if backend_name == "firestore":
            collection_name = f"{app.name}-{class_name.lower()}"
            storage_resources.append(
                f'# Firestore collection for {qname} (auto-created on first write)\n'
                f'firestore_collection_{class_name.lower()} = "{collection_name}"\n'
            )
            env_vars_pulumi.append(
                f'    gcp.cloudrun.ServiceTemplateSpecContainerEnvArgs(\n'
                f'        name="{env_var}",\n'
                f'        value=firestore_collection_{class_name.lower()},\n'
                f'    ),'
            )
        elif backend_name == "cloud-sql-postgres":
            instance_var = f"sql_{class_name.lower()}"
            storage_resources.append(
                f'{instance_var} = gcp.sql.DatabaseInstance(\n'
                f'    "{class_name.lower()}-sql",\n'
                f'    database_version="POSTGRES_16",\n'
                f'    region="{region}",\n'
                f'    settings=gcp.sql.DatabaseInstanceSettingsArgs(\n'
                f'        tier="db-f1-micro",\n'
                f'        backup_configuration=gcp.sql.DatabaseInstanceSettingsBackupConfigurationArgs(\n'
                f'            enabled=True,\n'
                f'        ),\n'
                f'    ),\n'
                f'    deletion_protection=False,\n'
                f'    opts=pulumi.ResourceOptions(depends_on=[]),\n'
                f')\n'
                f'{instance_var}_db = gcp.sql.Database(\n'
                f'    "{class_name.lower()}-db",\n'
                f'    instance={instance_var}.name,\n'
                f'    name="{app.name}",\n'
                f')\n'
            )
            env_vars_pulumi.append(
                f'    gcp.cloudrun.ServiceTemplateSpecContainerEnvArgs(\n'
                f'        name="{env_var}",\n'
                f'        value={instance_var}.connection_name.apply(\n'
                f'            lambda cn: f"postgresql://skaal@localhost/{app.name}?host=/cloudsql/{{cn}}"\n'
                f'        ),\n'
                f'    ),'
            )
        elif backend_name == "memorystore-redis":
            redis_var = f"redis_{class_name.lower()}"
            storage_resources.append(
                f'{redis_var} = gcp.redis.Instance(\n'
                f'    "{class_name.lower()}-redis",\n'
                f'    tier="BASIC",\n'
                f'    memory_size_gb=1,\n'
                f'    region="{region}",\n'
                f'    redis_version="REDIS_7_0",\n'
                f')\n'
            )
            env_vars_pulumi.append(
                f'    gcp.cloudrun.ServiceTemplateSpecContainerEnvArgs(\n'
                f'        name="{env_var}",\n'
                f'        value={redis_var}.host.apply(lambda h: f"redis://{{h}}:6379"),\n'
                f'    ),'
            )

    storage_resources_str = "\n".join(storage_resources)
    env_vars_pulumi_str = "\n".join(env_vars_pulumi)

    vpc_connector_block = ""
    if needs_vpc:
        vpc_connector_block = textwrap.dedent("""\
            vpc_connector = gcp.vpcaccess.Connector(
                "skaal-vpc-connector",
                name=f"{stack_name}-connector",
                region=region,
                ip_cidr_range="10.8.0.0/28",
                network="default",
            )
            vpc_connector_annotation = {
                "run.googleapis.com/vpc-access-connector": vpc_connector.name,
                "run.googleapis.com/vpc-access-egress": "private-ranges-only",
            }
        """)
        annotations_ref = "vpc_connector_annotation"
    else:
        vpc_connector_block = ""
        annotations_ref = "{}"

    pulumi_lines = [
        '"""',
        f"Pulumi stack generated by `skaal deploy`.",
        f"App: {app.name}  Target: gcp-cloudrun",
        "Do not edit manually — regenerate with `skaal deploy`.",
        '"""',
        "import pulumi",
        "import pulumi_gcp as gcp",
        "",
        "config = pulumi.Config()",
        "stack_name = pulumi.get_stack()",
        f'app_name = "{app.name}"',
        f'region = config.get("gcp:region") or "{region}"',
        f'project = config.require("gcp:project")',
        "",
        "# ── Artifact Registry Repository ─────────────────────────────────",
        "repo = gcp.artifactregistry.Repository(",
        '    "skaal-repo",',
        f'    repository_id=f"{{stack_name}}-{app.name}",',
        '    location=region,',
        '    format="DOCKER",',
        ")",
        "",
        "# ── Storage Resources ─────────────────────────────────────────────",
        storage_resources_str,
        vpc_connector_block,
        "# ── Cloud Run Service ────────────────────────────────────────────",
        "image = repo.name.apply(",
        f'    lambda r: f"{{region}}-docker.pkg.dev/{{project}}/{{r}}/{app.name}:latest"',
        ")",
        "",
        "cloud_run_service = gcp.cloudrun.Service(",
        '    "skaal-cloudrun",',
        f'    name=f"{{stack_name}}-{app.name}",',
        "    location=region,",
        "    template=gcp.cloudrun.ServiceTemplateArgs(",
        "        metadata=gcp.cloudrun.ServiceTemplateMetadataArgs(",
        f"            annotations={annotations_ref},",
        "        ),",
        "        spec=gcp.cloudrun.ServiceTemplateSpecArgs(",
        "            containers=[gcp.cloudrun.ServiceTemplateSpecContainerArgs(",
        "                image=image,",
        "                envs=[",
        env_vars_pulumi_str,
        "                ],",
        "                resources=gcp.cloudrun.ServiceTemplateSpecContainerResourcesArgs(",
        '                    limits={"memory": "512Mi", "cpu": "1000m"},',
        "                ),",
        "            )],",
        "        ),",
        "    ),",
        "    traffics=[gcp.cloudrun.ServiceTrafficArgs(",
        '        percent=100, latest_revision=True,',
        "    )],",
        ")",
        "",
        "# Allow public (unauthenticated) access",
        "gcp.cloudrun.IamMember(",
        '    "public-invoker",',
        "    service=cloud_run_service.name,",
        "    location=region,",
        '    role="roles/run.invoker",',
        '    member="allUsers",',
        ")",
        "",
        "# ── Exports ───────────────────────────────────────────────────────",
        'pulumi.export("service_url", cloud_run_service.statuses[0].url)',
        'pulumi.export("image_repository", repo.name)',
    ]
    pulumi_main_content = "\n".join(pulumi_lines) + "\n"

    pulumi_main_path = pulumi_dir / "__main__.py"
    pulumi_main_path.write_text(pulumi_main_content)
    generated.append(pulumi_main_path)

    # ── pulumi/Pulumi.yaml ─────────────────────────────────────────────────
    pulumi_yaml_content = textwrap.dedent(f"""\
        name: skaal-{app.name}
        runtime: python
        description: Generated by skaal deploy
    """)
    pulumi_yaml_path = pulumi_dir / "Pulumi.yaml"
    pulumi_yaml_path.write_text(pulumi_yaml_content)
    generated.append(pulumi_yaml_path)

    # ── README.md ─────────────────────────────────────────────────────────
    resource_list = []
    for qname, spec in plan.storage.items():
        class_name = qname.split(".")[-1]
        resource_list.append(
            f"- {spec.backend} backend: `{class_name.lower()}` (backend: {spec.backend})"
        )
    resource_list.append(f"- Cloud Run service: `{app.name}`")
    resource_list.append("- Artifact Registry repository")
    resource_list_str = "\n".join(resource_list)

    readme_content = textwrap.dedent(f"""\
        # Deploy {app.name} to GCP (Cloud Run)

        Generated by `skaal deploy`.

        ## Prerequisites
        - GCP project with billing enabled
        - `gcloud` CLI installed and authenticated (`gcloud auth application-default login`)
        - Docker installed (for building the container image)
        - Pulumi CLI installed (`pip install pulumi pulumi-gcp`)

        ## Deploy

        ```bash
        # 1. Build and push the container image
        PROJECT=your-gcp-project
        REGION={region}
        REPO=your-repo-name  # from `pulumi stack output image_repository`

        gcloud auth configure-docker ${{REGION}}-docker.pkg.dev
        docker build -t ${{REGION}}-docker.pkg.dev/${{PROJECT}}/${{REPO}}/{app.name}:latest .
        docker push ${{REGION}}-docker.pkg.dev/${{PROJECT}}/${{REPO}}/{app.name}:latest

        # 2. Deploy infrastructure
        cd pulumi
        pip install pulumi pulumi-gcp
        pulumi stack init dev
        pulumi config set gcp:project ${{PROJECT}}
        pulumi config set gcp:region ${{REGION}}
        pulumi up
        ```

        ## Resources created

        {resource_list_str}

        ## Notes

        - The Cloud Run service is publicly accessible (unauthenticated).
          Add IAM bindings to restrict access.
        - Firestore collections are created automatically on first write.
        - Set `GOOGLE_APPLICATION_CREDENTIALS` or use Workload Identity for auth.
    """)

    readme_path = output_dir / "README.md"
    readme_path.write_text(readme_content)
    generated.append(readme_path)

    return generated
