"""Rendering utilities for skaal deploy generators."""

from __future__ import annotations

import re
import string
from collections.abc import Mapping
from pathlib import Path
from typing import Any

_TEMPLATES_DIR = Path(__file__).parent.parent / "templates"
_BARE = re.compile(r"^[a-zA-Z0-9_-]+$")
_SPECIAL_VAL = re.compile(r'[{}\[\]:#|>&*!\'"]|^\s|\s$')
_RESERVED = re.compile(r"^(true|false|null|yes|no|on|off|~)$", re.I)


def render(template: str, **variables: str) -> str:
    path = _TEMPLATES_DIR / template
    return string.Template(path.read_text()).substitute(variables)


def _quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _yaml_key(key: str) -> str:
    return key if _BARE.match(key) else _quote(key)


def _yaml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if value is None:
        return "null"
    text = str(value)
    if not text or _SPECIAL_VAL.search(text) or _RESERVED.match(text):
        return _quote(text)
    return text


def _yaml_lines(data: Any, indent: int = 0) -> list[str]:
    pad = "  " * indent
    lines: list[str] = []

    if isinstance(data, dict):
        for key, value in data.items():
            rendered_key = _yaml_key(str(key))
            if isinstance(value, (dict, list)):
                lines.append(f"{pad}{rendered_key}:")
                lines.extend(_yaml_lines(value, indent + 1))
            else:
                lines.append(f"{pad}{rendered_key}: {_yaml_scalar(value)}")
    elif isinstance(data, list):
        for item in data:
            if isinstance(item, dict):
                entries = list(item.items())
                if not entries:
                    lines.append(f"{pad}- {{}}")
                    continue
                first_key, first_value = entries[0]
                rendered_key = _yaml_key(str(first_key))
                if isinstance(first_value, (dict, list)):
                    lines.append(f"{pad}- {rendered_key}:")
                    lines.extend(_yaml_lines(first_value, indent + 2))
                else:
                    lines.append(f"{pad}- {rendered_key}: {_yaml_scalar(first_value)}")
                for key, value in entries[1:]:
                    rendered_key = _yaml_key(str(key))
                    if isinstance(value, (dict, list)):
                        lines.append(f"{pad}  {rendered_key}:")
                        lines.extend(_yaml_lines(value, indent + 2))
                    else:
                        lines.append(f"{pad}  {rendered_key}: {_yaml_scalar(value)}")
            else:
                lines.append(f"{pad}- {_yaml_scalar(item)}")

    return lines


def to_pyproject_toml(
    app_name: str,
    deps: list[str],
    python_version: str = "3.11",
    uv_sources: dict[str, str] | None = None,
) -> str:
    dep_lines = "\n".join(f'    "{dependency}",' for dependency in deps)
    content = (
        f"# Generated by `skaal build`. Do not edit manually.\n"
        f"[project]\n"
        f'name = "{app_name}"\n'
        f'version = "0.1.0"\n'
        f'requires-python = ">={python_version}"\n'
        f"dependencies = [\n"
        f"{dep_lines}\n"
        f"]\n"
    )
    if uv_sources:
        content += "\n[tool.uv.sources]\n"
        for package, path in uv_sources.items():
            content += f'{package} = {{ path = "{path}" }}\n'
    return content


def to_pulumi_yaml(stack: Mapping[str, Any]) -> str:
    return "\n".join(_yaml_lines(stack)) + "\n"
